d8e-ai/lutra-plugin

slack/plugin.py, slack/plugin.toml
Add Slack plugin.  It is very simple.
=> Add Slack plugin

github/plugin.py, github/plugin.toml
Add GitHub plugin that only has one action, `github_pulls`, which returns results from the GitHub `pulls` API.
=> Add GitHub plugin

github/plugin.py
Add useful datetime fields: `{created_at,updated_at,merged_at,closed_at}`.
=> github: Add useful datetime fields

github/plugin.py
Default sorting to `"desc"`, as I think it is simple and makes sense.
=> github: Default sorting to `"desc"`

slack/plugin.py, slack/plugin.toml
Add the `slack_send_message_to_self` action, which sends a message to yourself from the Lutra bot.
=> slack: Add action to send a message to yourself

README.external.md
=> readme: Delete TODO about nested dataclasses

airtable/plugin.py
Make errors easier to interpret.  For example, if you are trying to update a record with fields that do not match the schema, the existing error message says:
```
[error] Client error '422 Unprocessable Entity' for URL 'https://api.airtable.com/v0/...' For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
```
This change makes the error say something like:
```
[error] 422: UNKNOWN_FIELD_NAME: Unknown field name: "Notes"
```
=> airtable: Make errors easier to interpret

airtable/plugin.py
- Allow users to pass through an Airtable URL
- Support typecast param when patching an airtable record
This is a breaking change and we will need to regenerate the Airtable example
=> Update airtable plugin

airtable/plugin.py
This seems less confusing and more consistent.  Most importantly, it was mostly authored by ChatGPT, so it must be good.
=> airtable: Improve airtable_parse_ids_from_url docstring

airtable/plugin.py
Use the `fields` parameter when listing records[1].  Calls to `listRecords` appear to validate that the set of fields exist in the schema, returning a `422` if any do not.  This simplifies everything a bit, as we now rely on Airtable to do the validation, and our existing error handling already fetches and includes the schema in the raised error.
This fixes the problem in which we would raise a false error because the API omits fields that have no values when returning records.
[1] https://airtable.com/developers/web/api/list-records
=> airtable: Use fields parameter when listing records

hubspot/plugin.py, hubspot/plugin.toml
Adds support for a few different contact APIs.
- List all your contacts.
- Create a new contact (for now, only supports creating with the basic properties - update contact is needed to update it with more properties.).
- Update a contact.
- Search for contacts.
=> Add HubSpot integration for a few API endpoints dealing with contacts.

hubspot/plugin.py
I used GPT a bit too much on the previous PR, sorry!
(it doesn't follow PEP, adds extra comments, shadows variables).  I should have been more careful!
=> Fix hubspot comments from Jerry

apollo/plugin.py
Update apollo people data enrichment api to more closely resemble the actual api.
Let's follow up later to add support for id after we add the people search endpoint since the ids have to work together.
=> Update Apollo plugin

hubspot/plugin.py
- Update company and deal list/search/update/create functions
=> HubSpot Plugin Updates

hubspot/plugin.py
- Update docstring
- Change dataclass union type to any
=> Update hubspot plugin

slack/plugin.py
=> slack: Add purposes

hubspot/plugin.py
Supporting Custom Properties in hubspot_search_contacts
=> HubSpot improvements

airtable/plugin.py
=> airtable: Add purpose annotations

hubspot/plugin.py
=> hubspot: Add purpose annotations

hubspot/plugin.py
"distutils" does not exist in Python 3.12, so I switched it to use Pydantic boolean parsing instead.
I also discovered while testing this that `properties.get("email", "")` returns `None` for contacts with no email, which causes a pydantic ValidationError while contstructing the HubSpotContact, so I fixed that too.
How I tested:
* I added a custom boolean property `test_boolean_property` to contacts in our HubSpot playground.
* `_coerce_properties_to_lutra`: I made a workflow that exports all the contacts to Google Sheets with a column for `test_boolean_property` property, and checked that it exported the values correctly.
* `_coerce_properties_to_hubspot`: I made a workflow that updates `test_boolean_property` and checked that it worked. (Note: Actually this doesn't work because the …
=> fix hubspot boolean handling and missing email case

hubspot/plugin.py
I changed `.raise_for_status()` to `raise_error_text`, which puts the response text in the error so that instead of just "400 bad request" you get useful information like this:
I also had to change everything to async because `raise_error_text` is async.
=> raises better errors from hubspot

hubspot/plugin.py
The main change is to always do `x.get(y) or z` instead of `x.get(y)`, `x[y]`, or `x.get(y, z)`.
Since the parsing happened in two different places for each type of hubspot object, I consolidated them, and this fixed some inconsistencies between the two parsers (lastmodifieddate vs hs_lastmodifieddate, id vs hs_object_id).
Testing: For each object type, I ran a workflow that fetched all the objects and checked that the results looked reasonable. Then, I modified each workflow to have a search condition (this triggers the other code path that I modified), and checked that the results still looked reasonable.
=> fix some optional properties in HubSpot plugin

hubspot/plugin.py
- Reformat files
- Fix type annotations in various places, most importantly in making HubSpotPaginationToken optional in search_contacts.
=> Fix typing issues in hubspot plugin

slack/plugin.py
When sending messages, the user list was being fetched so that @-mentions could use display names instead of Slack user IDs.  Fetching the user list uses the `users.list` API which has a [tier 2 rate limit](https://web.archive.org/web/20250114230805/https://api.slack.com/apis/rate-limits#tier_t2): ~20 requests per minute.  This is pretty easy to accidentally overwhelm.
Do this only if the message contains @-mentions.
=> slack: Fetch user list only when needed

airtable/plugin.py, apollo/plugin.py, github/plugin.py, slack/plugin.py, webhook/plugin.py, zoom/plugin.py
Switches all implementations to async / AsyncClient using AsyncAugmentedTransport, making sure to await response.aread().
Functions that needed to be converted were also converted.
=> Update all plugins to use AsyncAugmentedTransport

slack/plugin.py, slack/plugin.toml
Here's a proposal for what the Slack plugin could look like with an auth decorator interface based on an in person discussion.
This isn't exactly what's going on with my current implementation, but I could move it in this direction.
=> update slack to use inline auth

xero/plugin.py, xero/plugin.toml
=> Xero for rendering
