d8e-ai/lutra-plugin

github/plugin.py

Use `Literal` types for string arguments to help guide correct calling.

github: Use `Literal` types for string arguments

---

github/plugin.py

Make `state` parameter documentation not redundant with the type signature.

github: Make state parameter documentation not redundant

---

README.external.md
airtable/plugin.py

When we get a `422 Unprocessable Entity` error, try to fetch the involved table schema and include it in the error message.  This is both useful to humans and to LLMs, hopefully making it possible for things to fix themselves.

airtable: Include schema in 422 error messages

---

webhook/plugin.py
webhook/plugin.toml

This initial plugin implementation is very simple.  It does a bunch of simplifying things:
- Assumes `POST`.
- Assumes JSON request and response bodies.
- `body` and return are `Any`, so we won't get much typing help.
This is good enough to be used by a workflow with the description:
> Post a body of the form { "message": "Hello from Lutra and Zapier!"} to the webhook `https://hooks.zapier.com/hooks/catch/<elided>`. Allow only the message to be customizable.

webhook: Add initial webhook plugin

---

airtable/plugin.py

Allow specification of what fields to include when listing records.  This is a crude way for generated code to assert that the schema of a table is as it expects.
Airtable tables have field names.  When fetching data from Airtable, the generated code (possibly on its own or at your accidental direction) may try to access fields with names that do not exist, e.g.:
```python
records: list[AirtableRecord] = airtable_record_list(base_id, table_id)
person_values: List[str] = []
for record in records:
person_values.append(record.fields["First Name"])
```
where the records do not have a `"First Name"` field and instead have a `"Name"` field.
This is problematic because the code doesn't encounter an error until it tries to access the `"First Name"` field.  At that moment, it's hard to provide a …

airtable: Allow specification of what fields to include

---

airtable/plugin.py

Update `airtable_record_list` to support retrieving records by `view_id`
- Context: Code gen usually generates code that processes data in the order it is returned by `airtable_record_list` and the result to the user looks like this:
Update `airtable_record_list` docstring to be more accurate regarding what is returned in fields
- Code gen would sometimes generate code that checks for the existence of a field in the record:
See also: https://lutra.ai/run-debug/workflows/deW0k5xWHXs/018d8b5a-0319-82f7-9855-8e79ff87e627
- Updating the docstring to let code gen know that fields aren't always returned.

Update airtable plugin

---

github/plugin.py
github/plugin.toml
github/plugin_test.py

It's a bit tricky to test these actions because they require an authenticated wrapper.  However, the test mocks / injects a fake for the symbols / implementation to get things working, and pointing the APIs at public resources still works for the purposes of a test.  Though this hits a real API so is subject to rate limits from GitHub.  But it's okay for one-off testing (not CI, yet).
Let me know what you think or what alternatives might be worth pursuing!

Add github issues and comments fetching actions, and a test.

---

airtable/plugin.py

- Update prompt to make sure that an empty set isn't passed to include_fields when calling the function
- Update prompt to notify code_gen that a field that is unset will be excluded from the returned records
Workflow that used include_field because the prompt specified the fields: https://lutra.ai/workflows/bWYO7NR-gkA
Workflow that did not use the include_field because the we wanted to just return all the fields in a markdown table: https://lutra.ai/workflows/23TiTTwh5Qs

Update airtable_record_list function:

---

github/plugin.py

* Sometimes `obj["body"]` is `None`, and Pydantic gets angry when you try to put that in a non-optional `str` field.
* It is useful to have issue assignee.

Improve github issues plugin

---

github/plugin.py

The `body` field can be `null`.  See [documentation](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests).

github: Handle null pull request body field

---

airtable/plugin.py

Encourage code_gen to check for existence of fields before using a field. airtable fields that are unset do not get returned. This docstring tweak encourages code_gen to check for the existence of the field before accessing the value by the key.
Workflow affected: https://lutra.ai/workflows/h9FKkobgykU/versions/V1
Generated code snippet after docstring tweak:
```
attraction_name: str = record.fields.get("ATTRACTION_NAME", "")
try:
result: SearchResult = _search_genre_subgenre(attraction_name)
except Exception as e:
print(f"Error searching for {attraction_name}: {str(e)}")
continue
fields: Dict[str, Any] = {}
if result.is_sports:
fields["LutraGenre"] = "Sports"
if result.sport_type:
fields["LutraSubGenre"] = result.sport_type
else:
if result.genre:
fields["LutraGenre"] = result.genre
if …
```

Tweak airtable_record_list docstring

---

slack/plugin.py

Include a list of available channels in the error message.  Users will now see something like:
```text
[error] RuntimeError: channel `#does-not-exist` not found in channels: ['channel-that-does-exist', 'general', 'other-channel-that-does-exist']; double-check that you have authorized the correct workspace
```
Previously, they saw something like:
```text
[error] RuntimeError: fetching history: {'ok': False, 'error': 'channel_not_found'}
```

slack: Make channel_not_found error more informative

---

airtable/plugin.py

These are useful for incremental data sync and data processing:
* When the task is to sync data from an external source into airtable, there is often a way to query the external source for "records added after xxx". With the `sort` argument, you can get the "latest" record in the airtable, according to whatever task-specific field is right for querying the external source. Lutra seems to already understand this pretty well, in my own workflow all I had to say was "change it to only sync runs later than the latest run in the table" and it did the right thing.
* When the task is to fill in field(s), you can use `filter_by_formula` to find records that need their field filled in. This is better than using pagination, because it doesn't time out, and because it lets you resume from where you …

add sort and filter_by_formula args to airtable_record_list

---

hubspot/plugin.py

User used a HubSpot contact list with name "Lutra Test List #2"  and this was not escaped correctly.

Improve HubSpot list

---

hubspot/plugin.py

Instead of hardcoding properties to fetch and property types to coerce, uses the HubSpot properties API to get the properties, and then fetches _all_ of them.
Testing:
* All tests were done in our playground account. It's possible that real-world accounts will have more properties that run into some limits that we don't know about. We'll see...!
* I tested that hubspot_*_search actions still succeed and return reasonable-looking results.
* I tested that hubspot_update_contacts can successfully update string, number, datetime, and bool properties.
* I tested that hubspot_update_{companies|deals} can successfully update string properties.
* I wasn't able to find or create properties of type "date", but the HubSpot docs say that they exist, so I implemented them but didn't test them.

use API to get all HubSpot property data

---

slack/plugin.py

- Get conversation replies to a thread
- Convert user ids to display names if available.
Makes SlackUser object public and used in some APIs, since the mapping seems useful.
This allows a workflow that responds to an entire thread of replies, and can mention users (from their IDs alone).

Add two new actions to slack plugin.

---

slack/plugin.py

Bot messages don't have a user field but have a bot_id field, so use that when "user" doesn't exist.

Slack: Allow retreiving conversation history/replies from bots

---

slack/plugin.py

Updating slack_send_message_to_channel to assign a default value to the thread_ts argument.

Assign default to thread_ts

---

airtable/plugin.py

* Adds `airtable_get_base_schema` to allow chat to see the table schemas before operating on the tables.
* Does the same schema processing that we had in our existing airtable schema observe.
There are some things I was unsure about.
* Should I even define dataclasses for the schema? I could just return the whole JSON response as a `Any` or `dict[str, Any]`. I did try this, and it caused snippets to sometimes assume incorrect things about the response format, like looking for table schemas in `schema[table_id]`, and sometimes it even tried to get information about the schema out of it using `data_extractor`.
* Same question about the schemaless `options: dict[str, Any]` I have in my dataclass. Except for this one, I decided to keep it schemaless because (1) it seems to cause fewer …

airtable schema observe

---

hubspot/plugin.py

Plugin dataclass methods are not propagated/available during evaluation, so delete them to avoid the illusion.
(I will separately prevent dataclass methods from being saved in the first place).
We could also choose to support them, but given that it doesn't seem to be a problem, I am not worrying about it now.

hubspot: Delete dataclass methods, as they have no effect

---

hubspot/plugin.py

Update various search actions (contacts, companies, deals) to return results that match different IDS.
- Support OR queries in search (OR-of-ANDs boolean logic).
```
Get the hubspot {insert object type} with the list of ids: {list of ids}
Use hubspot_search_{object_type}
```

Update HubSpot search actions

---

airtable/plugin.py

Adds Airtable batch record creation.
Deprecate the old single-record API -- available for old code, but not new generations.
Implementation batches internally in up to 10 records as per the limit.  TODO to make each batch in async parallel...
In the future we can implement batch updating as well.

Add Airtable batch create records API.

---

slack/plugin.py

It looks nicer and is consistent with the "GitHub" and "Stripe" bots.
I've already made the change for the actual Slack app.  This changes a help/error message to be consistent.

slack: Rename Lutra bot to "Lutra"

---

airtable/plugin.py
airtable/plugin.toml
apollo/plugin.py
apollo/plugin.toml
github/plugin.py
github/plugin.toml
hubspot/plugin.py
hubspot/plugin.toml
slack/plugin.py
zoom/plugin.py
zoom/plugin.toml

Test and release "plan":
* airtable: I tested one action locally, and I will test one action after importing to prod.
* apollo: I won't test anything because I don't have an api key. This seems fine because this plugin doesn't get much usage.
* github: I tested one action locally, and I will test one action after importing to prod.
* hubspot: I will test one action after importing to prod. (It doesn't work locally I think).
* slack: I tested one action locally, and I will test one action after importing to prod.
* zoom: I won't test or import anything because this is not live in prod right now.

migrate the rest of our source-controlled plugins to inline auth
